import org.scalatest.{MustMatchers, WordSpec}
import scudoku.{Grid, parser, solver}

class ParserTest extends WordSpec with MustMatchers {
  "parse" when {
    "empty" must {
      "return empty grid" in {
        val grid = parser.parseGrid(
          """
            |... ... ...
            |... ... ...
            |... ... ...
            |
            |... ... ...
            |... ... ...
            |... ... ...
            |
            |... ... ...
            |... ... ...
            |... ... ...
          """.stripMargin)
        grid must contain(Grid.emptyGrid)
      }
    }
    "invalid number of cells" must {
      "return None" in {
        val grid = parser.parseGrid(
          """
            |123 123 ...
            |456 456 ...
            |789 789 ...
            |
            |... ... ...
            |... ... ...
            |... ... ...
          """.stripMargin)
        grid mustBe 'empty
      }
    }
  }
}
